spring.application.name=channeldoc-api

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/channeldoc_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=test123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Google OAuth Configuration
google.client-id=493525059532-h30ha384beed739ogdslh15trf6u2b13.apps.googleusercontent.com
# JWT Configuration
jwt.secret=TRZRp6FyPVp+M/BG3LlK9LtqCoiFJwKo+AZ7ha3TFGI=
jwt.expiration-ms=86400000
