package com.medisync.channeldoc_api.model.enums;

public enum Specialization {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC,
    PEDIATRICIAN,
    PSYCHIATRIST,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    DENTIST,
    ENT_SPECIALIST,
    ONCOLOGIST,
    UROLOGIST,
    GASTROENTEROLOGIST,
    ENDOCRINOLOGIST,
    PULMONOLOGIST,
    RHEUMATOLOGIST,
    NEPHROLOGIST
}
